services:
  dadatafinder:
    build: .
    ports:
      - 8501:8501
    volumes:
      - "./data.db:/app/data.db"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"