services:
  dadatafinder:
    build: .
    ports:
      - 8501:8501
    volumes:
      - "./data.db:/app/data.db"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8501/" ]
      interval: 30s
      timeout: 5s
      retries: 3