name: Streamlit Check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Streamlit
        run: |
          streamlit run main.py &
          sleep 10

      - name: Verify Streamlit is running
        run: |
          curl -f http://localhost:8501 || exit 1
  build_and_push:
    name: Push Docker image
    runs-on: ubuntu-latest
    needs: test-streamlit
    permissions:
      contents: read

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Log in to the Docker registry
        uses: docker/login-action@v2
        with:
          registry: registry.socialcode.ru
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: registry.socialcode.ru/dadatafinder/app
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y ssh

      - name: Connect and deploy on the server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 194.87.161.47 >> ~/.ssh/known_hosts
          ssh xoleryter@194.87.161.47 << 'EOF'
            cd /home/xoleryter/dadatafiner
            docker compose -f compose.template.yaml down
            docker compose -f compose.template.yaml up -d
          EOF
