name: Streamlit Check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  SERVER_HOST: 194.87.161.47
  SERVER_USER: xoleryter
  SERVER_PATH: /dadatafiner
jobs:
  deploy:
    runs-on: ubuntu-latest
    #needs: build_and_push
    steps:
      - name: login ssh
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.SSH_PRIVATE_KEY }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
      - name: Connect and deploy on the server
        run: |
          ssh -T xoleryter@194.87.161.47 << 'EOF'
            docker compose -f /home/xoleryter/dadatafiner/compose.template.yaml down
            docker compose -f /home/xoleryter/dadatafiner/compose.template.yaml up -d
          EOF



