name: Streamlit Check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    #needs: build_and_push
    steps:
      - name: login ssh
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: 194.87.161.47
          username: xoleryter
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: |
            docker compose -f /home/xoleryter/dadatafiner/compose.template.yaml down;docker compose -f /home/xoleryter/dadatafiner/compose.template.yaml up
      - name: Install SSH Client
        run: sudo apt-get update && sudo apt-get install -y ssh

      - name: Connect and deploy on the server
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh -T xoleryter@194.87.161.47
          docker compose -f /home/xoleryter/dadatafiner/compose.template.yaml down
          docker compose -f /home/xoleryter/dadatafiner/compose.template.yaml up

