name: Streamlit Check
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-streamlit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Start Streamlit
        run: |
          streamlit run main.py &
          sleep 10

      - name: Verify Streamlit is running
        run: |
          curl -f http://localhost:8501 || exit 1
  build_and_push:
    name: Push Docker image
    runs-on: ubuntu-latest
    needs: test-streamlit
    permissions:
      contents: read

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Log in to the Docker registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.MY_DOCKER }}
          password: ${{ secrets.MY_DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: xoleryter/app:latest
